### ISSUE TITLE
Decode HTML Entities by default

### ISSUE THREAD

**Issue by sdegetaus** [AxeWP/wp-graphql-rank-math#50]
### What problem does this address?

When getting the values from the GraphQL, the titles and descriptions with HTML entities (such as – and &) are rendered as `&ndash;` and `&amp;` respectively.

I think the plugin should display them ready-to-use by the frontend instead of the backend or frontend decoding them.   

### What is your proposed solution?

The obvious solution would be to decode them when passing them to the GraphQL.

### What alternatives have you considered?

An alternative, is to do the decoding myself with RankMath's filters. For example, to decode the SEO title you can simply add these lines of code: 
```
add_filter('rank_math/frontend/title', function ($title) {
  return html_entity_decode($title);
});
```
Nonetheless, I would still prefer that the plugin did this by default.
Let me know if you disagree and why 🙂

**Comment by justlevine** [comment]
Hey @sdegetaus - this is a great idea!

I'm not sure if it's safe to apply by default _across the board_ ( ref: https://github.com/wp-graphql/wp-graphql/issues/1035 ), but mosy are likely fine.

Since as you noted this does currently have a workaround, I'm going to slate this for a future improvement after we hit v0.1.0, but I'm happy to review any PRs if you (or anyone else) want to beat me to it.

PS: this issue is eligible for my [WPGraphQL Spring Cleaning campaign](https://axepress.dev/spring), where I'm donating dev hours for for issues/PRs to the WPGraphQL project/feature of your choice. If you're interested, fill out the link above and let me know what I should work on.
