### ISSUE TITLE
Interface Error in WPGraphQL IDE

### ISSUE THREAD

**Issue by robbiebel** [AxeWP/wp-graphql-rank-math#99]
### Description

Hello, firstly thank you for this plugin.

I'm getting error in GraphQL IDE even before run a query.

### Steps to reproduce

1. Go to WPGraphQL IDE

### Additional context

`{
  "errors": [
    "Interface field ContentNode.seo expects type RankMathContentNodeSeo but ProductVariation.seo is type RankMathSeo.",
    "Interface field Product.seo expects type RankMathProductObjectSeo but VariableProduct.seo is type RankMathSeo.",
    "Interface field ContentNode.seo expects type RankMathContentNodeSeo but VariableProduct.seo is type RankMathSeo.",
    "Interface field Product.seo expects type RankMathProductObjectSeo but ExternalProduct.seo is type RankMathSeo.",
    "Interface field ContentNode.seo expects type RankMathContentNodeSeo but ExternalProduct.seo is type RankMathSeo.",
    "Interface field Product.seo expects type RankMathProductObjectSeo but GroupProduct.seo is type RankMathSeo.",
    "Interface field ContentNode.seo expects type RankMathContentNodeSeo but GroupProduct.seo is type RankMathSeo.",
    "Interface field Product.seo expects type RankMathProductObjectSeo but SimpleProduct.seo is type RankMathSeo.",
    "Interface field ContentNode.seo expects type RankMathContentNodeSeo but SimpleProduct.seo is type RankMathSeo.",
    "Interface field ContentNode.seo expects type RankMathContentNodeSeo but SimpleProductVariation.seo is type RankMathSeo."
  ]
}`

![Screenshot from 2024-07-14 16-35-38](https://github.com/user-attachments/assets/367b523b-1a48-4886-bb92-b1f65a226179)

### Plugin Version

0.3.0

### WordPress Version

6.5.5

### WPGraphQL Version

1.27.0

### RankMath SEO Version

1.0.221

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for RankMath SEO, WPGraphQL, and WPGraphQL for Rank Math

- [X] Yes
- [ ] My issue is with a specific 3rd-party plugin.

**Comment by justlevine** [comment]
Hey @robbiebel - thanks for taking the time to report this.

In your report you ticked that you've disabled all other plugins except for Rank Math, WPGraphQL, and this plugin, yet your error message points to `ProductVariation`, `GroupProduct` and other WPGraphQL objects that are not native to WordPress or those plugins.

First: please disable _all_ other external plugins (or custom code if that's how youre exposing those CPTs/Terms) and confirm the problem goes away.

Then: 
- If you're using custom code, please share the code you are using to register those types/expose them to WPGraphQL.
- Please send the list of your minimally-replicable active plugins (test them one at a time to figure out one causes the error to return) along with their version numbers.

Once we have that, we should be able to figure out the next steps to get this resolved for you.

**Comment by robbiebel** [comment]
Hey @justlevine,

Thank you for fast reply. Sorry, I thought WooGraphQL was required plugin for WPGraphQLRankMath.

After I disable WooGraphQL the error is gone.

Can you give me first sight idea because you have knowledge about interfaces?

I'm really sorry for your time. I'm closing the issue.

Thank you

**Comment by justlevine** [comment]
Okay, so that seems to point to an issue with WooGraphQL's types not getting properly mapped to their resolved object type for `seo` and instead using the base interface

Would need to investigate further to see why exactly this is happening.

Can you please share the version of WooCommerce and WooGraphQL you have active?

**Comment by robbiebel** [comment]
WPGraphQL Version 1.27.0
WPGraphQL WooCommerce (WooGraphQL) Version 0.20.0
WooCommerce Version 9.1.2
Rank Math SEO with AI SEO Tools Version 1.0.223
WPGraphQL for Rank Math SEO Version 0.3.0

No any other plugin is active.

**Comment by justlevine** [comment]
Thanks! Would you be able to update to the latest WPGraphQL (v1.27.2) and confirm the issue persists? Iirc 1.27.x had some fixes specifically for interfaces.

**Comment by robbiebel** [comment]
Yes I confirm that the error still persist with WpGraphQL Version 1.27.2

**Comment by justlevine** [comment]
On further investigation, this is due to a combination of factors:

1. WPGraphQL core has a bug where interface fields cannot be narrowed down by the child object type. https://github.com/wp-graphql/wp-graphql/issues/3096
   - To work around that bug, we [use the `graphql_${object_type}_fields` filter](https://github.com/justlevine/wp-graphql-rank-math/blob/483435f138e70429a2202fdb6bbd4627322cede7/src/Utils/Utils.php#L75-L87) to apply the narrowed-type (E.g. `RankMathProductObjectSeo`.
2. WPGraphQL for WooCommerce handles Post Type registration by using `graphql_post_entities_allowed_post_types` to [hide some WooCommerce CPTs](https://github.com/wp-graphql/wp-graphql-woocommerce/blob/d7a2ba332009e113e100e892722ea5e4ce06a4a7/includes/class-core-schema-filters.php#L190) using a custom `skip_graphql_type_registry` key. 
3. As a result, Woocommerce CPTs don't get returned by `WPGraphQL::allowed_post_types()` which is what we're using to detect the types (correctly, I believe 🧐) before applying the WPGraphQL-core workaround [here](https://github.com/justlevine/wp-graphql-rank-math/blob/483435f138e70429a2202fdb6bbd4627322cede7/src/Type/WPObject/SeoObjects.php#L37).

To be honest, I'm not entirely sure the best way to fix.

As a temporary workaround, we can check for WooGraphQL and manually apply the expected types, but that's too flaky to support long-term and probably wouldnt work for custom Woo product CPTs.

Long-term, addressing https://github.com/wp-graphql/wp-graphql/issues/3096 in would allow us to drop our workaround, but the interface inheritance lifecycle is one of the more fragile areas of the codebase, so no idea when that might happen.

Similarly, its _possible_ that something could be done in WooGraphQL so the built-in type registration is skipped but we can still depend on `WPGraphQL::allowed_post_types()` and other core methods (if that's even a correct assumption that those "child" CPTs be included), or perhaps theres a WooGraphQL-specific workaround that will allow us to automagically get the all woo CPTs that are exposed to the schema _even if they're not type registered_.
